version: "3"

services:
  calendar-sync:
    build: .
    environment:
      - VIRTUAL_HOST=calendar-sync.lenders.dev
      - LETSENCRYPT_HOST=calendar-sync.lenders.dev
    expose:
      - 80
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    # Disable this during local development
    external:
      name: reverse-proxy_external
