version: "3"

services:
  calendar-sync:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calendar-sync.rule=Host(`calendar-sync.lenders.dev`)"
      - "traefik.http.routers.calendar-sync.tls=true"
      - "traefik.http.routers.calendar-sync.tls.certresolver=myresolver"
